name: Compile LaTeX Document

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clean Auxiliary Files
      run: |
        cd src
        rm -f *.aux *.bcf *.fls *.log *.bbl *.blg *.out

    - name: Compile LaTeX Document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        args: -pdf
        working_directory: src

    - name: Upload Compiled PDF
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: src/main.pdf
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
  
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/main.pdf
        asset_name: main.pdf
        asset_content_type: application/pdf
