name: Compile LaTeX Document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clean Auxiliary Files
      run: |
        cd src
        rm -f *.aux *.bcf *.fls *.log *.bbl *.blg *.out

    - name: Compile LaTeX Document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        args: -pdf
        working_directory: src

    - name: Upload Compiled PDF
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: src/main.pdf
